# Generated by Django 5.0.3 on 2024-04-03 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(help_text='Слово, которое нужно отгадать', max_length=40, verbose_name='Слово')),
                ('is_guessed', models.BooleanField(default=False, help_text='Флаг, указывающий, было ли слово отгадано', verbose_name='Отгадано')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи', verbose_name='Дата создания')),
                ('creator', models.ForeignKey(help_text='Пользователь, который создал слово', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Слово',
                'verbose_name_plural': 'Слова',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_closed', models.BooleanField(default=False, help_text='Флаг, указывающий, закрыта ли комната для новых участников', verbose_name='Комната закрыта')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи', verbose_name='Дата создания')),
                ('creator', models.ForeignKey(help_text='Пользователь, который создал комнату', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('word', models.ForeignKey(help_text='Слово, которое отгадывается в комнате', on_delete=django.db.models.deletion.CASCADE, to='main.word', verbose_name='Слово')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
            },
        ),
        migrations.CreateModel(
            name='GuessedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(help_text='Слово, предложенное для отгадывания в комнате', max_length=40, verbose_name='Предложенное слово')),
                ('is_similar', models.CharField(help_text='Процент совпадения с предполагаемым словом.', max_length=8, verbose_name='Схожесть')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания записи', verbose_name='Дата создания')),
                ('creator', models.ForeignKey(help_text='Пользователь, который предложил слово', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('room', models.ForeignKey(help_text='Комната, в которой было предложено слово', on_delete=django.db.models.deletion.CASCADE, to='main.room', verbose_name='Комната')),
                ('word_id', models.ForeignKey(help_text='Идентификатор слова, которое отгадывается', on_delete=django.db.models.deletion.CASCADE, to='main.word', verbose_name='Слово')),
            ],
            options={
                'verbose_name': 'Предложенное слово',
                'verbose_name_plural': 'Предложенные слова',
            },
        ),
    ]
