# Generated by Django 5.0.3 on 2024-04-08 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_guessedword_is_similar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['-created_at'], 'verbose_name': 'Слово', 'verbose_name_plural': 'Слова'},
        ),
    ]
