# Generated by Django 5.0.3 on 2024-04-08 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_word_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-created_at', 'is_closed'], 'verbose_name': 'Комната', 'verbose_name_plural': 'Комнаты'},
        ),
    ]
